-- Ejecutar una sola vez en Supabase > SQL Editor.
-- Este esquema guarda una fila por visita y conserva su timestamp.

create table if not exists public.uagrm_visitas (
    id bigint generated by default as identity primary key,
    modulo_id integer not null,
    modulo_nombre text not null,
    visitado_en timestamptz not null default timezone('utc', now())
);

create index if not exists uagrm_visitas_modulo_id_idx
    on public.uagrm_visitas (modulo_id);

create index if not exists uagrm_visitas_visitado_en_idx
    on public.uagrm_visitas (visitado_en desc);

create or replace view public.uagrm_visitas_ranking as
select
    modulo_id,
    max(modulo_nombre) as modulo_nombre,
    count(*)::bigint as visitas,
    max(visitado_en) as ultima_visita
from public.uagrm_visitas
group by modulo_id;

grant select on public.uagrm_visitas_ranking to anon, authenticated;
grant insert on public.uagrm_visitas to anon, authenticated;

alter table public.uagrm_visitas enable row level security;

drop policy if exists "uagrm_visitas_public_insert" on public.uagrm_visitas;
create policy "uagrm_visitas_public_insert"
    on public.uagrm_visitas
    for insert
    to anon, authenticated
    with check (
        modulo_id > 0
        and char_length(modulo_nombre) between 1 and 200
    );