-- Esquema compatible con la tabla de resumen usada por este proyecto.
-- Ejecutar solo si la tabla todavía no existe, en Supabase > SQL Editor.

create table if not exists public.uagrm_visitas (
    id bigint generated by default as identity primary key,
    modulo_id text not null unique,
    nombre text not null,
    visitas integer not null default 0,
    ultima_visita timestamptz
);

create index if not exists uagrm_visitas_visitas_idx
    on public.uagrm_visitas (visitas desc);

grant select, insert, update on public.uagrm_visitas to anon, authenticated;
grant usage, select on sequence public.uagrm_visitas_id_seq to anon, authenticated;

alter table public.uagrm_visitas enable row level security;

drop policy if exists "uagrm_visitas_public_read" on public.uagrm_visitas;
create policy "uagrm_visitas_public_read"
    on public.uagrm_visitas
    for select
    to anon, authenticated
    using (true);

drop policy if exists "uagrm_visitas_public_insert" on public.uagrm_visitas;
create policy "uagrm_visitas_public_insert"
    on public.uagrm_visitas
    for insert
    to anon, authenticated
    with check (
        modulo_id ~ '^modulo_[0-9]+$'
        and char_length(nombre) between 1 and 200
        and visitas >= 0
    );

drop policy if exists "uagrm_visitas_public_update" on public.uagrm_visitas;
create policy "uagrm_visitas_public_update"
    on public.uagrm_visitas
    for update
    to anon, authenticated
    using (true)
    with check (
        modulo_id ~ '^modulo_[0-9]+$'
        and char_length(nombre) between 1 and 200
        and visitas >= 0
    );